/**
 * AI Generated Recipe Screen - Recipe generated by OpenAI
 */

import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Ionicons } from '@expo/vector-icons';
import { colors, typography, spacing } from '../../theme';
import type { RootStackParamList } from '../../navigation/types';
import { parseRecipeFromText } from '../../services/openai/openaiService';
import { ParsedRecipe } from '../../types/recipe';
import { NutritionInfo } from '../../types/nutrition';

type NavigationProp = NativeStackNavigationProp<RootStackParamList>;

// Mock nutrition data - in production, calculate from ingredients
const calculateNutrition = (recipe: ParsedRecipe): NutritionInfo => {
  // Simple estimation based on ingredients
  const estimatedCalories = recipe.ingredients.length * 80;
  const estimatedProtein = recipe.ingredients.filter(ing => 
    ing.category === 'protein' || ing.name.toLowerCase().includes('frango') || 
    ing.name.toLowerCase().includes('peixe') || ing.name.toLowerCase().includes('ovo')
  ).length * 20;
  
  return {
    calories: estimatedCalories,
    protein: estimatedProtein,
    carbohydrates: estimatedCalories * 0.4 / 4,
    fats: estimatedCalories * 0.3 / 9,
    fiber: recipe.ingredients.filter(ing => 
      ing.category === 'vegetable' || ing.name.toLowerCase().includes('integral')
    ).length * 3,
  };
};

export default function AIGeneratedRecipeScreen() {
  const navigation = useNavigation<NavigationProp>();
  const [loading, setLoading] = useState(true);
  const [recipe, setRecipe] = useState<ParsedRecipe | null>(null);
  const [nutrition, setNutrition] = useState<NutritionInfo | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    generateRecipe();
  }, []);

  const generateRecipe = async () => {
    setLoading(true);
    setError(null);
    
    try {
      // Generate a random recipe prompt
      const prompts = [
        'Crie uma receita saudável e saborosa de frango grelhado com legumes',
        'Receita de salada de quinoa com vegetais e molho de limão',
        'Receita fitness de omelete de claras com espinafre e queijo',
        'Receita de salmão assado com batata doce e brócolis',
        'Receita de smoothie bowl com frutas e granola',
      ];
      
      const randomPrompt = prompts[Math.floor(Math.random() * prompts.length)];
      
      // Use OpenAI to generate recipe
      const generatedRecipe = await parseRecipeFromText(randomPrompt);
      setRecipe(generatedRecipe);
      
      // Calculate nutrition
      const calculatedNutrition = calculateNutrition(generatedRecipe);
      setNutrition(calculatedNutrition);
    } catch (err: any) {
      console.error('Error generating recipe:', err);
      setError(err.message || 'Erro ao gerar receita');
    } finally {
      setLoading(false);
    }
  };

  const handleViewDetail = () => {
    if (recipe && nutrition) {
      navigation.navigate('RecipeDetailModal', {
        recipeId: recipe.id,
        recipe,
        nutrition,
      });
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container} edges={['top']}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
          >
            <Ionicons name="arrow-back" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.title}>Receita IA</Text>
        </View>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Gerando receita com IA...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (error) {
    return (
      <SafeAreaView style={styles.container} edges={['top']}>
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
          >
            <Ionicons name="arrow-back" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.title}>Receita IA</Text>
        </View>
        <View style={styles.errorContainer}>
          <Ionicons name="alert-circle-outline" size={48} color={colors.state.error} />
          <Text style={styles.errorText}>{error}</Text>
          <TouchableOpacity style={styles.retryButton} onPress={generateRecipe}>
            <Text style={styles.retryButtonText}>Tentar novamente</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  if (!recipe) {
    return null;
  }

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
        >
          <Ionicons name="arrow-back" size={24} color={colors.text.primary} />
        </TouchableOpacity>
        <Text style={styles.title}>Receita IA</Text>
        <TouchableOpacity style={styles.refreshButton} onPress={generateRecipe}>
          <Ionicons name="refresh-outline" size={24} color={colors.primary} />
        </TouchableOpacity>
      </View>

      <ScrollView
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Recipe Preview Card */}
        <View style={styles.previewCard}>
          <View style={styles.previewHeader}>
            <View style={styles.aiBadge}>
              <Ionicons name="sparkles" size={16} color={colors.primary} />
              <Text style={styles.aiBadgeText}>Gerado por IA</Text>
            </View>
          </View>
          
          <Text style={styles.recipeTitle}>{recipe.title}</Text>
          {recipe.description && (
            <Text style={styles.recipeDescription}>{recipe.description}</Text>
          )}

          {/* Quick Info */}
          <View style={styles.quickInfo}>
            {recipe.servings && (
              <View style={styles.infoItem}>
                <Ionicons name="people-outline" size={16} color={colors.text.quaternary} />
                <Text style={styles.infoText}>{recipe.servings} porções</Text>
              </View>
            )}
            {recipe.totalTime && (
              <View style={styles.infoItem}>
                <Ionicons name="time-outline" size={16} color={colors.text.quaternary} />
                <Text style={styles.infoText}>{recipe.totalTime} min</Text>
              </View>
            )}
            {nutrition && (
              <View style={styles.infoItem}>
                <Ionicons name="flame-outline" size={16} color={colors.primary} />
                <Text style={styles.infoText}>{Math.round(nutrition.calories)} kcal</Text>
              </View>
            )}
          </View>

          {/* Nutrition Preview */}
          {nutrition && (
            <View style={styles.nutritionPreview}>
              <View style={styles.nutritionItem}>
                <Text style={styles.nutritionValue}>{Math.round(nutrition.protein)}g</Text>
                <Text style={styles.nutritionLabel}>Proteína</Text>
              </View>
              <View style={styles.nutritionItem}>
                <Text style={styles.nutritionValue}>{Math.round(nutrition.carbohydrates)}g</Text>
                <Text style={styles.nutritionLabel}>Carboidratos</Text>
              </View>
              <View style={styles.nutritionItem}>
                <Text style={styles.nutritionValue}>{Math.round(nutrition.fats)}g</Text>
                <Text style={styles.nutritionLabel}>Gorduras</Text>
              </View>
            </View>
          )}

          {/* Ingredients Preview */}
          <View style={styles.ingredientsPreview}>
            <Text style={styles.sectionTitle}>Ingredientes ({recipe.ingredients.length})</Text>
            <View style={styles.ingredientsList}>
              {recipe.ingredients.slice(0, 5).map((ingredient) => (
                <View key={ingredient.id} style={styles.ingredientPreview}>
                  <Text style={styles.ingredientPreviewText}>
                    • {ingredient.name} {ingredient.amount > 0 && `${ingredient.amount}${ingredient.unit}`}
                  </Text>
                </View>
              ))}
              {recipe.ingredients.length > 5 && (
                <Text style={styles.moreText}>
                  +{recipe.ingredients.length - 5} ingredientes
                </Text>
              )}
            </View>
          </View>

          {/* CTA Button */}
          <TouchableOpacity
            style={styles.viewDetailButton}
            onPress={handleViewDetail}
            activeOpacity={0.9}
          >
            <Text style={styles.viewDetailButtonText}>Ver receita completa</Text>
            <Ionicons name="arrow-forward" size={20} color={colors.buttonText} />
          </TouchableOpacity>
        </View>

        {/* Info Card */}
        <View style={styles.infoCard}>
          <Ionicons name="information-circle-outline" size={24} color={colors.primary} />
          <Text style={styles.infoCardText}>
            Esta receita foi gerada por inteligência artificial. Você pode gerar uma nova receita clicando no ícone de atualizar.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.base,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  title: {
    ...typography.styles.h2,
    color: colors.text.primary,
  },
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  content: {
    paddingHorizontal: spacing.base,
    paddingBottom: spacing['3xl'],
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
  },
  loadingText: {
    ...typography.styles.body,
    color: colors.text.quaternary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
    paddingHorizontal: spacing.xl,
  },
  errorText: {
    ...typography.styles.body,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: 12,
    marginTop: spacing.md,
  },
  retryButtonText: {
    ...typography.styles.bodySemibold,
    color: colors.buttonText,
  },
  previewCard: {
    backgroundColor: colors.card,
    borderRadius: 24,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
    marginTop: spacing.md,
  },
  previewHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: spacing.md,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.primaryLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  aiBadgeText: {
    ...typography.styles.caption,
    fontSize: 11,
    fontWeight: typography.fontWeight.semibold,
    color: colors.primary,
  },
  recipeTitle: {
    ...typography.styles.h2,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  recipeDescription: {
    ...typography.styles.body,
    color: colors.text.secondary,
    marginBottom: spacing.md,
    lineHeight: 22,
  },
  quickInfo: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.lg,
    flexWrap: 'wrap',
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  infoText: {
    ...typography.styles.small,
    color: colors.text.quaternary,
  },
  nutritionPreview: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: colors.neutral.light1,
    borderRadius: 16,
    padding: spacing.md,
    marginBottom: spacing.lg,
  },
  nutritionItem: {
    alignItems: 'center',
  },
  nutritionValue: {
    ...typography.styles.h4,
    color: colors.text.primary,
    marginBottom: spacing.xs,
  },
  nutritionLabel: {
    ...typography.styles.caption,
    color: colors.text.quaternary,
  },
  ingredientsPreview: {
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    ...typography.styles.bodySemibold,
    color: colors.text.primary,
    marginBottom: spacing.sm,
  },
  ingredientsList: {
    gap: spacing.xs,
  },
  ingredientPreview: {
    paddingLeft: spacing.sm,
  },
  ingredientPreviewText: {
    ...typography.styles.body,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  moreText: {
    ...typography.styles.small,
    color: colors.primary,
    fontStyle: 'italic',
    marginTop: spacing.xs,
  },
  viewDetailButton: {
    backgroundColor: colors.button,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.md,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  viewDetailButtonText: {
    ...typography.styles.bodySemibold,
    fontSize: 16,
    color: colors.buttonText,
  },
  infoCard: {
    flexDirection: 'row',
    backgroundColor: colors.neutral.light1,
    borderRadius: 16,
    padding: spacing.md,
    gap: spacing.sm,
    marginTop: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoCardText: {
    ...typography.styles.small,
    color: colors.text.secondary,
    flex: 1,
    lineHeight: 18,
  },
});

